from typing import Any


ZHAOPIN_SEARCH_URL = "https://www.zhaopin.com/sou/"

FIFTYONE_SEARCH_URL = "https://we.51job.com/pc/search"

ENV_FILE_NAME = ".env"

DEFAULT_CONFIG: dict[str, Any] = {
    "keywords": ["数据分析"],
    "regions": [],
    "default_regions": ["北京", "上海", "广州", "深圳", "杭州"],
    "max_pages_per_region": 5,
    "max_empty_page_retries": 2,
    "headless": False,
    "user_agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "viewport": {"width": 1400, "height": 900},
    "delay_seconds": {
        "after_open_search": [1.0, 2.0],
        "between_pages": [0.8, 1.5],
        "retry_reload": [2.5, 4.0],
        "between_tasks": [2.5, 4.5],
        "before_next_page": [0.5, 1.0],
        "after_next_page": [1.0, 1.8],
        "long_break": [6.0, 10.0],
        "before_open_detail": [0.8, 1.6],
        "after_open_detail": [1.8, 3.0],
        "between_details": [0.9, 1.8],
        "detail_retry": [2.5, 4.5],
    },
    "typing_delay_ms": [40, 100],
    "retry_backoff_factor": 1.7,
    "max_retry_delay_seconds": 36.0,
    "max_detail_retries": 1,
    "detail_page_timeout_ms": 90000,
    "long_break_every_pages": 5,
    "long_break_probability": 0.2,
    "output_dir": "output",
    "crawled_links_dir": "",
    "platform": "zhaopin",
    "manual_auth": False,
    "auth_wait_seconds": 120,
    "auth_state_path": "auth/51job_state.json",
    "login_51job": False,
    "user_data_dir": "auth/51job_profile",
    "login_zhaopin": False,
    "zhaopin_user_data_dir": "auth/zhaopin_profile",
    "browser_backend": "playwright",
    "gologin_token": "",
    "gologin_profile_id": "",
    "adspower_api_key": "",
    "adspower_api_port": "50325",
    "scrapling_real_chrome": False,
    "scrapling_google_search": False,
    "scrapling_block_webrtc": True,
    "scrapling_hide_canvas": True,
    "skip_detail_fetch": True,
    "auto_restart_on_verify": False,
    "max_restart_attempts": 3,
    "yescaptcha_proxy": "",
}

EMPTY_CELL_VALUE = "/"

OUTPUT_COLUMNS = [
    "招聘平台",
    "岗位类型一级",
    "岗位类型二级",
    "岗位名称",
    "岗位类型企业/公务员/事业单位/军队文职",
    "公司名称",
    "公司规模",
    "所在省份",
    "城市",
    "详细地址",
    "学历要求",
    "经验要求",
    "薪资范围",
    "福利标签",
    "工作内容",
    "任职要求",
    "岗位链接",
    "发布时间",
    "投递起始时间",
    "投递截止时间",
    "证书要求",
    "备注",
]

CITY_PROVINCE_MAP = {
    "北京": "北京市",
    "上海": "上海市",
    "天津": "天津市",
    "重庆": "重庆市",
    "广州": "广东省",
    "深圳": "广东省",
    "珠海": "广东省",
    "佛山": "广东省",
    "东莞": "广东省",
    "中山": "广东省",
    "惠州": "广东省",
    "杭州": "浙江省",
    "宁波": "浙江省",
    "温州": "浙江省",
    "嘉兴": "浙江省",
    "绍兴": "浙江省",
    "南京": "江苏省",
    "苏州": "江苏省",
    "无锡": "江苏省",
    "常州": "江苏省",
    "南通": "江苏省",
    "成都": "四川省",
    "绵阳": "四川省",
    "武汉": "湖北省",
    "长沙": "湖南省",
    "合肥": "安徽省",
    "芜湖": "安徽省",
    "福州": "福建省",
    "厦门": "福建省",
    "泉州": "福建省",
    "济南": "山东省",
    "青岛": "山东省",
    "烟台": "山东省",
    "郑州": "河南省",
    "洛阳": "河南省",
    "西安": "陕西省",
    "咸阳": "陕西省",
    "沈阳": "辽宁省",
    "大连": "辽宁省",
    "长春": "吉林省",
    "哈尔滨": "黑龙江省",
    "石家庄": "河北省",
    "太原": "山西省",
    "呼和浩特": "内蒙古自治区",
    "南昌": "江西省",
    "南宁": "广西壮族自治区",
    "海口": "海南省",
    "贵阳": "贵州省",
    "昆明": "云南省",
    "兰州": "甘肃省",
    "西宁": "青海省",
    "银川": "宁夏回族自治区",
    "乌鲁木齐": "新疆维吾尔自治区",
    "拉萨": "西藏自治区",
    "香港": "香港特别行政区",
    "澳门": "澳门特别行政区",
}

FIFTYONE_CITY_CODE_MAP = {
    "北京": "010000",
    "上海": "020000",
    "广州": "030200",
    "深圳": "040000",
    "武汉": "180200",
    "西安": "200200",
    "杭州": "080200",
    "南京": "070200",
    "成都": "090200",
    "重庆": "060000",
    "东莞": "030800",
}
